name: "Un Denis Presque Parfait"
version: "0.1.7"
slug: "denis_presque_parfait"
description: "Jeu de notation familial - MVP live input"
url: "https://github.com/toi/denis_presque_parfait"
arch:
  - aarch64
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:silverware-fork-knife
panel_title: "Denis Presque Parfait"
map:
  - addon_config:rw
options: {}
schema: {}